<?php if(!empty($flashMessages)) :?>

<?php foreach ($flashMessages as $Message) : ?>
    <p class="alert alert-danger"><?=$Message;?></p>
<?php endforeach; ?>

<?php endif; ?>

<div class="container rounded p-5" id="FormMembre">
                <form action="add_account.php" method="POST">
                    <div class="form-group">
                        <label for="lastname">LastName</label>
                        <input required type="text" class="form-control" name="lastname" id="lastname" value="<?=$First_name??'';?>" /> <!-- Permet d'enregistrer le nom && prenom si le formulaire n'est pas valider pour permmetre à l'utilisateur de ne pas retaper ces informations -->
                    </div>
                    <div class="form-group">
                        <label for="firstname">FirstName</label>
                        <input required type="text" class="form-control" name="firstname" id="firstname"/>
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input required type="email" class="form-control" id="email" aria-describedby="emailHelp" name="email">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input required minlength="8" type="password" class="form-control" id="pass" name="password">
                    </div>
                    <button type="submit" class="btn btn-primary">Créer un compte</button>
            </form>
</div>