<section class="container">
    <h2></h2>
    <form action="create_product.php" method="post">
        <div class="form-group">
            <label for="name">Nom du produit</label>
            <input type="text" class="form-control" id="name" name="name" >
        </div>
        <div class="form-group">
            <label for="description">Description produit</label>
            <input type="text" class="form-control" id="description" name="description">
        </div>
        <div class="form-group">
            <label for="picture">Picture</label>
            <input type="text" class="form-control" id="picture" name="picture">
        </div>
        <div class="form-group">
            <label for="stock">Stock</label>
            <input type="text" class="form-control" id="stock" name="stock">
        </div>
        <div class="form-group">
            <label for="category">Catégory</label>
            <input type="text" class="form-control" id="stock" name="category">
        </div>
        <div class="form-group">
            <label for="creator">Creator</label>
            <input type="text" class="form-control" id="stock" name="creator">
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Mettre en tendance</label>
        </div>
        <button type="submit" class="btn btn-primary mt-3 mb-3">Créer un produit</button>
    </form>
</section>