<?php if(!empty($flashMessages)) :?>

<?php foreach ($flashMessages as $Message) : ?>
    <p class="alert alert-success"><?=$Message;?></p>
<?php endforeach; ?>

<?php endif; ?>


<section class="row">
    <?php foreach ($products as $product): ?>
        <article class="col-md-3">
            <div class="card mb-4 mx-1">
                <img class="card-img-top" src="images/<?=$product['picture'];?>" alt="">
                <div class="card-body">
                    <h2 class="card-title"><?=$product['name'];?></h2>
                    <span class="badge badge-secondary"><?=$product['label'];?></span>
                    <?php if ($product['stock'] <= 5): ?>
                        <p class="card-text">Il ne reste plus que <?=$product['stock'];?> exemplaire(s) !</p>
                    <?php endif; ?>
                    <p class="card-text"><?=$product['price'];?> €</p>
                    <div class="mt-2">
                        <a href="product.php?id=<?=$product['id'];?>" class="btn btn-primary">Voir le produit</a>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    Proposé par <span><?=$product['shop_name'];?></span>
                </div>
            </div>
        </article>
    <?php endforeach; ?>
</section>
            