<section class="container">
    <h2></h2>
    <form action="create_product.php" method="POST">
        <div class="form-group">
            <label for="name">Nom du produit</label>
            <input type="text" class="form-control" id="name" name="name" value="<?=$results['name'];?>" >
        </div>
        <div class="form-group">
            <label for="description">Description produit</label>
            <input type="text" class="form-control" id="description" name="description" value="<?=$results['description'];?>">
        </div>
        <div class="form-group">
            <label for="picture">Picture</label>
            <input type="text" class="form-control" id="picture" name="picture" value="<?=$results['picture'];?>">
        </div>
        <div class="form-group">
            <label for="stock">Stock</label>
            <input type="text" class="form-control" id="stock" name="stock" value="<?=$results['stock'];?>">
        </div>
        <div class="form-group">
            <label for="prix">Prix en €</label>
            <input type="text" class="form-control" id="prix" name="price" value="<?=$results['price'];?>">
        </div>
        <div class="form-group">
            <label for="category">Catégory</label>
            <select class="form-control" id="category" name="category">
                <option value="1">Petit_Filtre</option>
                <option value="2">Tuyaux</option>
                <option value="3">Medium_Filtre</option>
                <option value="4">Large_Filtre</option>
                <option value="5">Filtre_raw</option>
            </select>
        </div>
        <div class="form-group">
        <label for="creator">Creator</label>
            <select class="form-control" id="creator" name="creator">
                <option value="1">Raw</option>
                <option value="2">Pyragreen</option>
                <option value="3">Zamnésia</option>
            </select>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Mettre en tendance</label>
        </div>
        <button type="submit" class="btn btn-primary mt-3 mb-3">Créer un produit</button>
    </form>
</section>